### ISSUE TITLE
Error: The <Image> component cannot contain children

### ISSUE THREAD

**Issue by jariwalabhavesh** [Bhoos/react-native-theming#9]
It is giving image error in react native 50 above
I am using RN 0.55.3
![screenshot_1531286751](https://user-images.githubusercontent.com/10993666/42552282-45140048-84f9-11e8-89c0-ff7267a89447.png)

**Comment by syaau** [comment]
@jariwalabhavesh, I have just published v1.0.16 and included Theme.ImageBackground that encapsulates ImageBackground. You should be able to replace Image with ImageBackground now. Also just a note that ImageBackground requires width and height on style otherwise it throws an error, so just make sure that you have a style added to ImageBackground.

Also, you could have created custom themed component that are not available in the library itself using `createThemedComponent` method.

**Comment by jariwalabhavesh** [comment]
Thanks for quick fix
